CREATE TABLE CUST(
    Cno NUMBER(5) PRIMARY KEY,
    MeterNo Number(5) UNIQUE,
    Prev_Reading NUMBER(5),
    Current_Reading NUMBER(5),
    Units Number(5),
    Bill_Amount Number(5)
    );
    
INSERT INTO CUST VALUES(89, 100, 300, 800,0,0);
INSERT INTO CUST VALUES(67, 101, 790, 1000,0,0);
INSERT INTO CUST VALUES(90, 200, 800, 1200,0,0);
INSERT INTO CUST VALUES(62, 789, 200, 800,0,0);
INSERT INTO CUST VALUES(70, 899, 3200, 8700,0,0);
INSERT INTO CUST VALUES(66, 500, 3000, 9800,0,0);

SELECT * FROM CUST;


-- ANSWER 1

DECLARE
    REC CUST%ROWTYPE;
    B Number;
    U Number;
    Extra Number;
BEGIN 
    SELECT * INTO REC FROM CUST WHERE Cno =89;
    U:= REC.Current_Reading - REC.Prev_Reading;
        IF U<100 THEN
            B:=U*0.5;
        ELSE 
            EXTRA:=U-100;
            B:=100*0.5 + EXTRA*0.75; 
        END IF;
    UPDATE CUST SET Units=U, Bill_Amount=B WHERE Cno=89;
END;
SELECT * FROM CUST;

-- ANSWER 2
DECLARE 
    CURSOR C1 IS SELECT * FROM CUST;
    B NUMBER;
    U NUMBER;
    EXTRA NUMBER;
BEGIN
    FOR REC IN C1 LOOP
        U:= REC.Current_Reading - REC.Prev_Reading;
        IF U<100 THEN
            B:=U*0.5;
        ELSE 
            EXTRA:=U-100;
            B:=100*0.5 + EXTRA*0.75; 
        END IF;
        UPDATE CUST SET Units=U, Bill_Amount=B WHERE Cno=REC.Cno;
    END LOOP;
END;  
SELECT * FROM CUST;

-- Answer 3 

CREATE TABLE EMP(
    EMPNO NUMBER(3) PRIMARY KEY,
    ENAME CHAR(30),
    JOB CHAR(20),
    OLD_SAL NUMBER(5),
    NEW_SAL NUMBER(5),
    DEPTNO NUMBER(2)
    );
INSERT INTO EMP VALUES(3, 'SHRESHTH' ,'STUD',23545,null,20);
INSERT INTO EMP VALUES(5, 'JOHN DOE' ,'PROF',92645,null,20);
INSERT INTO EMP VALUES(7, 'SARAH DOE' ,'AS. PROF',20345,null,20);
INSERT INTO EMP VALUES(9, 'JANE DOE' ,'PROF',90345,null,10);
INSERT INTO EMP VALUES(17, 'JAMIE DOE' ,'PROF',90345,null,10);
INSERT INTO EMP VALUES(11, 'MEGAN DOE' ,'PROF',80345,null,30);
INSERT INTO EMP VALUES(13, 'FOX BROWN' ,'PROF',70345,null,30);
INSERT INTO EMP VALUES(15, 'R. HASTINGS' ,'PROF',60345,null,30);

SELECT * FROM EMP;

DECLARE 
    CURSOR C1 IS SELECT * FROM EMP;
    B NUMBER;

BEGIN
    FOR REC IN C1 LOOP
        B:= 0;
        IF REC.DEPTNO = 10 THEN
            B:= REC.OLD_SAL + 1000;
        ELSE IF REC.DEPTNO = 20 THEN
            B:= REC.OLD_SAL + 500;
        ELSE IF REC.DEPTNO = 30 THEN
            B:= REC.OLD_SAL + 800;
        ELSE 
            dbms_output.put_line('Not to be Updated Dept');
        END IF;
        END IF;
        END IF;

        UPDATE EMP SET NEW_SAL=B WHERE EMPNO=REC.EMPNO;
    END LOOP;
END;  

-- Answer 4

CREATE TABLE STUD(
    RNO NUMBER(3) PRIMARY KEY,
    MARKS_SUBJECT1 NUMBER(3),
    MARKS_SUBJECT2 NUMBER(3),
    MARKS_SUBJECT3 NUMBER(3),
    MARKS_SUBJECT4 NUMBER(3),
    TOTAL NUMBER(3),
    PERCENT DECIMAL(10,3)
    );
INSERT INTO STUD VALUES(1 ,100,100,100,100,NULL, NULL);
INSERT INTO STUD VALUES(2 ,54,45,40,80,NULL, NULL);
INSERT INTO STUD VALUES(3 ,70,10,90,100,NULL, NULL);
INSERT INTO STUD VALUES(4 ,98,20,80,100,NULL, NULL);
INSERT INTO STUD VALUES(5 ,60,100,10,70,NULL, NULL);


DECLARE 
    CURSOR C1 IS SELECT * FROM STUD;
    B NUMBER;
    A DECIMAL(10,3);
BEGIN
    FOR REC IN C1 LOOP
        B:= REC.MARKS_SUBJECT1 + REC.MARKS_SUBJECT2 + REC.MARKS_SUBJECT3 + REC.MARKS_SUBJECT4;
        A:= (B*100/400);

        UPDATE STUD SET TOTAL=B, PERCENT=A WHERE RNO=REC.RNO;
    END LOOP;
END;
SELECT * FROM STUD;


-- ANSWER 5
CREATE TABLE STUD(
    RNO NUMBER(3) PRIMARY KEY,
    MARKS_SUBJECT1 NUMBER(3),
    MARKS_SUBJECT2 NUMBER(3),
    MARKS_SUBJECT3 NUMBER(3),
    MARKS_SUBJECT4 NUMBER(3),
    TOTAL NUMBER(3),
    PERCENT DECIMAL(10,3)
    );
INSERT INTO STUD VALUES(1 ,100,100,100,100,NULL, NULL);
INSERT INTO STUD VALUES(2 ,54,45,40,80,NULL, NULL);
INSERT INTO STUD VALUES(3 ,70,10,90,100,NULL, NULL);
INSERT INTO STUD VALUES(4 ,98,20,80,100,NULL, NULL);
INSERT INTO STUD VALUES(5 ,60,100,10,70,NULL, NULL);



SELECT COALESCE(MARKS_SUBJECT1,0) + COALESCE(MARKS_SUBJECT2,0) + COALESCE(MARKS_SUBJECT3,0) + COALESCE(MARKS_SUBJECT4,0) FROM STUD
SELECT ((COALESCE(MARKS_SUBJECT1,0) + COALESCE(MARKS_SUBJECT2,0) + COALESCE(MARKS_SUBJECT3,0) + COALESCE(MARKS_SUBJECT4,0))*100)/400 FROM STUD


CREATE VIEW STUD_VIEW AS
SELECT RNO, MARKS_SUBJECT1, MARKS_SUBJECT2, MARKS_SUBJECT3, MARKS_SUBJECT4
FROM STUD;

SELECT * FROM STUD_VIEW

UPDATE STUD SET
    TOTAL= COALESCE(T.MARKS_SUBJECT1,0) + COALESCE(T.MARKS_SUBJECT2,0) + COALESCE(T.MARKS_SUBJECT3,0) + COALESCE(T.MARKS_SUBJECT4,0),
    PERCENT= ((COALESCE(T.MARKS_SUBJECT1,0) + COALESCE(T.MARKS_SUBJECT2,0) + COALESCE(T.MARKS_SUBJECT3,0) + COALESCE(T.MARKS_SUBJECT4,0))*100)/400
FROM 
(
    SELECT RNO, MARKS_SUBJECT1, MARKS_SUBJECT2, MARKS_SUBJECT3, MARKS_SUBJECT4
    FROM STUD
    GROUP BY RNO
) T
WHERE STUD.RNO= T.RNO

UPDATE STUD SET
    TOTAL= COALESCE(STUD_VIEW.MARKS_SUBJECT1,0) + COALESCE(STUD_VIEW.MARKS_SUBJECT2,0) + COALESCE(STUD_VIEW.MARKS_SUBJECT3,0) + COALESCE(STUD_VIEW.MARKS_SUBJECT4,0),
    PERCENT= ((COALESCE(STUD_VIEW.MARKS_SUBJECT1,0) + COALESCE(STUD_VIEW.MARKS_SUBJECT2,0) + COALESCE(STUD_VIEW.MARKS_SUBJECT3,0) + COALESCE(STUD_VIEW.MARKS_SUBJECT4,0))*100)/400
FROM 
STUD_VIEW
WHERE STUD.RNO= STUD_VIEW.RNO;



DECLARE
B NUMBER(5):=0;
S STUD%ROWTYPE;
C NUMBER(3);
A NUMBER(5,2);
BEGIN
    SELECT COUNT(*) INTO C FROM STUD;
    FOR i IN 1..C LOOP
        SELECT * INTO S FROM STUD WHERE ROWID IN (SELECT ROWID FROM STUD WHERE ROWNUM<=i MINUS SELECT ROWID FROM STUD WHERE ROWNUM<i);
        B := S.MARKS_SUBJECT1+S.MARKS_SUBJECT2+S.MARKS_SUBJECT3+S.MARKS_SUBJECT4;
        A := (B/400)*100;
        UPDATE STUD SET TOTAL=B,PERCENT=A WHERE RNO=S.RNO;
        END LOOP;
END;


-- ANSWER 6
DECLARE
    CURSOR C1 (d number) IS 
    SELECT * FROM EMP WHERE DEPTNO=d;
    REC C1%ROWTYPE;
BEGIN 
    OPEN C1(20);
    LOOP
        FETCH C1 INTO REC;
        EXIT WHEN C1%NOTFOUND;
        dbms_output.put_line(' EMPNO :' || REC.EMPNO || ' | ENAME :' || REC.ENAME || ' | JOB :' || REC.JOB || ' | SALARY: ' || REC.NEW_SAL);
    END LOOP;
    CLOSE C1;
END;

-- ANSWER 7

DECLARE
    CURSOR C1 (d number) IS 
        SELECT * FROM EMP 
        FETCH FIRST d ROWS ONLY;
    REC C1%ROWTYPE;
    TOTAL_SAL NUMBER(10):= 0;
BEGIN 
    OPEN C1(7);
    LOOP
        FETCH C1 INTO REC;
            EXIT WHEN C1%NOTFOUND;
        dbms_output.put_line(' EMPNO :' || REC.EMPNO || ' | ENAME :' || REC.ENAME || ' | JOB :' || REC.JOB || ' | SALARY: ' || REC.NEW_SAL);
        TOTAL_SAL:= TOTAL_SAL + REC.NEW_SAL;
    END LOOP;
    CLOSE C1;
    dbms_output.put_line('TOTAL AMOUNT:'|| TOTAL_SAL);
END;